# Generated by Django 3.0.4 on 2020-03-28 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VacationLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normal_days', models.IntegerField(blank=True, null=True)),
                ('children_days', models.IntegerField(blank=True, null=True)),
                ('request_days', models.IntegerField(blank=True, null=True)),
                ('employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('Urlop wypoczynkowy', 'Urlop wypoczynkowy'), ('Urlop okolicznościowy', 'Urlop okolicznościowy'), ('Urlop na żądanie', 'Urlop na żądanie'), ('Urlop opieka nad dzieckiem', 'Urlop opieka nad dzieckiem'), ('Urlop bezpłatny', 'Urlop bezpłatny')], max_length=100, null=True)),
                ('leave_date', models.DateField()),
                ('return_date', models.DateField()),
                ('comment', models.CharField(blank=True, max_length=300, null=True)),
                ('status', models.CharField(blank=True, choices=[('Zaakceptowany', 'Zaakceptowany'), ('W oczekiwaniu', 'W oczekiwaniu'), ('Odrzucony', 'Odrzucony')], default='W oczekiwaniu', max_length=100, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
