# Generated by Django 3.0.4 on 2020-04-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('Vacation leave', 'Vacation leave'), ('Occasional holidays', 'Occasional holidays'), ('Vacation on demand', 'Vacation on demand'), ('Vacation childcare', 'Vacation childcare'), ('Unpaid leave', 'Unpaid leave')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(blank=True, choices=[('Accept', 'Accepted'), ('Pending', 'Pending'), ('Reject', 'Rejected')], default='Pending', max_length=100, null=True),
        ),
    ]
