# Generated by Django 3.0.4 on 2020-04-13 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_auto_20200412_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='ActionLeave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, null=True)),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave.Leave')),
            ],
        ),
    ]
