# Generated by Django 3.0.4 on 2020-04-14 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_auto_20200414_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectLeave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, null=True)),
                ('leave', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='leave.Leave')),
            ],
        ),
    ]
