# Generated by Django 3.0.4 on 2020-04-17 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0006_auto_20200414_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveNotificationEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.TextField(null=True)),
                ('status', models.CharField(choices=[('Add', 'Add'), ('Accept', 'Accept'), ('Reject', 'Reject')], max_length=100, null=True)),
                ('read', models.BooleanField(default=False)),
                ('date_read', models.DateTimeField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('leave', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='leave.Leave')),
            ],
        ),
    ]
