# Generated by Django 3.0.4 on 2020-04-17 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leave', '0007_leavenotificationemployee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptleave',
            name='leave',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='leave.Leave'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leavenotificationemployee',
            name='leave',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leave.Leave'),
        ),
        migrations.AlterField(
            model_name='leavenotificationemployee',
            name='status',
            field=models.CharField(choices=[('Add', 'Add'), ('Add Employee', 'Add Employee'), ('Accept', 'Accept'), ('Accept Employee', 'Accept Employee'), ('Reject', 'Reject'), ('Reject Employee', 'Reject Employee')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rejectleave',
            name='leave',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='leave.Leave'),
        ),
    ]
