# Generated by Django 3.0.4 on 2020-04-21 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leave', '0009_auto_20200417_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavenotificationemployee',
            name='status',
        ),
        migrations.AddField(
            model_name='leavenotificationemployee',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
